# -*- coding: utf-8 -*-
"""Data Cleaning/Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_DLEiXgDo9EhICEw2tdaqGNYjU67EdN
"""

import pandas as pd

df = pd.read_csv('/content/raw_dataset.csv')
df = df.drop(columns=['Unnamed: 0'])
df.head(5)

"""FILLING THE NAN VALUES"""

#FILL ALL NAN VALUES
df = df.fillna('')

"""RENAMING THE COLUMNS"""

#RENAME COLUMN
df = df.rename(columns={df.columns[6]: 'tarpas'})

df.rename(columns = {'Usaha dibidang apa yang anda jalani?':'jenis_usaha',
                     'Hewan ternak apa yang anda ternakkan saat ini?':'hewan_ternak',
                     'Dimanakah lokasi geografis peternakan anda?':'lokasi_geografis',
                     'Menurut anda, haruskah seorang peternak mengerti perilaku hewan?':'mengerti_hewan',
                     'Berapa luas lahan yang anda miliki untuk peternakan anda?':'luas_lahan',
                     'Usaha kuliner apa yang sedang anda jalankan?':'usaha_kuliner',
                     'Bagaimana anda menjalankan usaha kuliner?':'tipe_usaha_kuliner',
                     'Menurut Anda kemampuan dasar memasak apa yang diperlukan untuk memulai usaha seperti anda?':'kemampuan_masak',
                     'Barang apa yang anda jual sebagai seorang dropshipper?':'barang_dropship',
                     'Dimana anda menyimpan barang dropshipping?':'penyimpanan_barang',
                     'Berapa pengeluaran internet anda selama satu bulan untuk keperluan usaha tersebut?':'biaya_internet',
                     'Sosial media apa yang anda gunakan untuk menjalankan usaha anda?':'sosial_media',
                     'Barang seperti apa yang anda jual ditoko?':'barang_toserba',
                     'Apakah anda memiliki toko sendiri':'toko_toserba',
                     'Jenis Toko?':'tipe_toko',
                     'Usaha apa yang anda jalankan saat ini?':'usaha_lain',
                     'Usaha seperti apa yang sedang anda jalani saat ini?':'tipe_usaha_lain'}, inplace = True)

"""COMBINING COLUMNS INTO ONE """

#COMBINING COLUMN
df['lokasi'] = df['Dimana lokasi anda berjualan?'] + df['lokasi_geografis'] + df['Dimana lokasi anda berjualan?.1'] + df['Dimana lokasi usaha Anda berjalan?']
df['Modal'] = df['Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha sebagai peternak?'] + df['Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha sebagai pengusaha kuliner?'] + df['Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha sebagai Dropshipper?'] + df['Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha toserba?'] + df['Berdasarkan pengalaman anda, berapakah modal yang diperlukan untuk menjalankan usaha tersebut?']
df['tingkat_persaingan'] = df['Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?'] + df['Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.1'] + df['Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.2'] + df['Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.3'] + df['Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.4']
df['jumlah_pegawai'] = df['Berapakah jumlah pegawai saat ini?'] + df['Berapakah jumlah pegawai saat ini?.1'] + df['Berapakah jumlah pegawai saat ini?.2'] + df['Berapakah jumlah pegawai saat ini?.3'] + df['Berapakah jumlah pegawai saat ini?.4']
df['omset'] = df['Berapa kira-kira keuntungan anda saat panen?'] + df['Berapa kira-kira omset anda dalam 1 bulan?'] + df['Berapa kira-kira omset anda dalam 1 bulan?.1'] + df['Berapa kira-kira omset anda dalam 1 bulan?.2'] + df['Berapa kira-kira omset anda dalam 1 bulan?.3']
df['target_pasar'] = df['tarpas'] + df['Kepada siapa anda menjual makanan/minuman anda? '] + df['Kepada siapa target pasar anda? '] + df['Kepada siapa target pasar anda? .1'] + df['Kepada siapa target pasar anda? .2']

"""REPLACE THE VALUES/SAMPLES"""

#REPLACING VALUES 

#Toserba/Toko Kelontong
df['jenis_usaha'] = df['jenis_usaha'].replace(['Pedagang','toko kelontong dan peternakan'],
                                              ['Toserba/Toko Kelontong','Toserba/Toko Kelontong']).astype(str)
#Kuliner
df['jenis_usaha'] = df['jenis_usaha'].replace(['Cake and cookies ','Minuman Es Teh'],
                                              ['Kuliner','Kuliner']).astype(str)
#Pakaian
df['jenis_usaha'] = df['jenis_usaha'].replace(['Toko baju/online shop','Pakaian anak','Pakaian Muslim','Busana'],
                                              ['Pakaian','Pakaian','Pakaian','Pakaian']).astype(str)
#Elektronik
df['jenis_usaha'] = df['jenis_usaha'].replace(['Toko Komputer','Toko Elektronik','Toko elektronik','Toko hp','Toko komputer','Toko laptop dan komputer','Toko handphone'],
                                              ['Elektronik','Elektronik','Elektronik','Elektronik','Elektronik','Elektronik','Elektronik']).astype(str)
#Barang Digital
df['jenis_usaha'] = df['jenis_usaha'].replace(['Pulsa','Google Play Card','Digital Goods','Penjualan akun'],
                                              ['Barang Digital','Barang Digital','Barang Digital','Barang Digital']).astype(str)
#others jobs
df['jenis_usaha'] = df['jenis_usaha'].replace(['Tidak tau','pebolahan air minum isi ulang','CV'],
                                              ['Jasa Mengajar','Jasa Isi Ulang Air Minum','Perseroan Komanditer']).astype(str)
#lokasi
df['lokasi'] = df['lokasi'].replace(['Dataran tinggi (pegunungan, bukit, lereng gunung)','Dataran rendah (rawa, sawah)','Rumah',''],
                                    ['Pedesaan/Perkampungan','Pedesaan/Perkampungan','Perkotaan','Perkotaan']).astype(str)

#lokasi_geografis
df['lokasi_geografis'] = df['lokasi_geografis'].replace(['Dataran tinggi (pegunungan, bukit, lereng gunung)','Dataran rendah (rawa, sawah)','Rumah',''], 
                                                        ['DT','DR','R','no_info']).astype(str)

#mengerti_hewan
df['mengerti_hewan'] = df['mengerti_hewan'].replace(['Sangat Perlu','Perlu','Kurang Perlu',''],
                                                    ['SP','P','KP','no_info']).astype(str)

#luas_lahan
df['luas_lahan'] = df['luas_lahan'].replace([''], ['no_info']).astype(str)

#usaha_kuliner
df['usaha_kuliner'] = df['usaha_kuliner'].replace([''], ['no_info']).astype(str)

#tipe_usaha_kuliner
df['tipe_usaha_kuliner'] = df['tipe_usaha_kuliner'].replace(['Tempat Permanen','Pesan Antar','Keliling','lewat sistem pre-order untuk sekarang ini.', ''],
                                                            ['TP','PA','K','PO','no_info']).astype(str)

#kemampuan_masak
df['kemampuan_masak'] = df['kemampuan_masak'].replace(['Perlu','Sangat perlu','Kurang perlu','Tidak perlu', ''],
                                                      ['P','SP','KP','TP','no_info']).astype(str)

#barang_dropship
df['barang_dropship'] = df['barang_dropship'].replace([''],['no_info']).astype(str)

#penyimpanan_barang
df['penyimpanan_barang'] = df['penyimpanan_barang'].replace([''],['no_info']).astype(str)

#biaya_internet
df['biaya_internet'] = df['biaya_internet'].replace([''],['no_info']).astype(str)

#sosial_media
df['sosial_media'] = df['sosial_media'].replace(['Instagram','Whatsapp','Shopee, Tokopedia', ''],['IG','WA','ECOM','no_info']).astype(str)

#barang_toserba
df['barang_toserba'] = df['barang_toserba'].replace([''],['no_info']).astype(str)

#toko_toserba
df['toko_toserba'] = df['toko_toserba'].replace(['','Iya','Tidak(Menyewa)'],['no_info','TRUE','FALSE']).astype(str)

#tipe_toko
df['tipe_toko'] = df['tipe_toko'].replace([''],['no_info']).astype(str)

#usaha_lain
df['usaha_lain'] = df['usaha_lain'].replace([''],['no_info']).astype(str)

#tipe_usaha_lain
df['tipe_usaha_lain'] = df['tipe_usaha_lain'].replace(['','Didalam ruangan','Diluar ruangan'],['no_info','IN','EX']).astype(str)

"""MAKING NEW COLUMNS"""

#MAKING NEW COLUMNS

#modal_minimum
df['modal_minimum'] = df['Modal'].replace(['1jt - 10 jt','10 - 25jt','< 1jt', '> 25jt'],['1000000','10000000','500000','25000000']).astype(float)

#modal_maximum
df['modal_maximum'] = df['Modal'].replace(['1jt - 10 jt','10 - 25jt','< 1jt', '> 25jt'],['10000000','25000000','1000000','100000000']).astype(float)

#tingkat_persaingan_idx
df['tingkat_persaingan_idx'] = df['tingkat_persaingan'].replace(['Rendah','Sedang','Tinggi'],['0','1','2']).astype(int)

#pegawai_minimum
df['pegawai_minimum'] = df['jumlah_pegawai'].replace(['2-4 orang','1 orang (Anda sendiri)','5-9 orang','Diatas 10 orang'],['2','1','5','10']).astype(int)

#omset_minimum
df['omset_minimum'] = df['omset'].replace(['< 10 Juta','25-50 Juta','10-25 Juta','> 50 Juta','10-50 Juta'],['1000000','35000000','10000000','50000000','25000000']).astype(float)

#target_pasar_per_category
df['tp_b'] = df['target_pasar'].replace(['Masyarakat golongan bawah;Masyarakat golongan menengah;Masyarakat golongan atas',
                                         'Masyarakat golongan bawah;Masyarakat golongan menengah',
                                         'Masyarakat golongan menengah;Masyarakat golongan atas',
                                         'Masyarakat golongan menengah',
                                         'Pasar tradisional',
                                         'Masyarakat golongan bawah',
                                         'Perusahaan (menyetor ke perusahaan pangan)',
                                         'Toko online',
                                         'Masyarakat Setempat',
                                         'Masyarakat golongan atas',
                                         'Pecinta burung','Restoran'],['1','1','0','0','1','1','1','1','1','0','1','1']).astype(int)
df['tp_m'] = df['target_pasar'].replace(['Masyarakat golongan bawah;Masyarakat golongan menengah;Masyarakat golongan atas',
                                         'Masyarakat golongan bawah;Masyarakat golongan menengah',
                                         'Masyarakat golongan menengah;Masyarakat golongan atas',
                                         'Masyarakat golongan menengah',
                                         'Pasar tradisional',
                                         'Masyarakat golongan bawah',
                                         'Perusahaan (menyetor ke perusahaan pangan)',
                                         'Toko online',
                                         'Masyarakat Setempat',
                                         'Masyarakat golongan atas',
                                         'Pecinta burung','Restoran'],['1','1','1','1','1','0','1','1','1','0','1','1']).astype(int)
df['tp_a'] = df['target_pasar'].replace(['Masyarakat golongan bawah;Masyarakat golongan menengah;Masyarakat golongan atas',
                                         'Masyarakat golongan bawah;Masyarakat golongan menengah',
                                         'Masyarakat golongan menengah;Masyarakat golongan atas',
                                         'Masyarakat golongan menengah',
                                         'Pasar tradisional',
                                         'Masyarakat golongan bawah',
                                         'Perusahaan (menyetor ke perusahaan pangan)',
                                         'Toko online',
                                         'Masyarakat Setempat',
                                         'Masyarakat golongan atas',
                                         'Pecinta burung','Restoran'],['1','0','1','0','1','0','1','1','1','1','1','1']).astype(int)
#hewan_ternak_sud
df['hewan_ternak_sub'] = df['hewan_ternak'].replace(
    ['Sapi','Kerbau rawa','Kambing','Sapi dan Kambing', #Sapi/Kambing/Kerbau
     'Ayam','Bebek','Ayam petelur','Ayam kampung','Burung Puyuh','Burung hias', #Unggas
     'Ikan Bawal','Ikan Toman','Ikan hias','Ikan hias air tawar','Lele','Ikan Lele','Ikan Hias', #Ikan
     'Ternak Lobster','Lobster',
     ''], #Udang
     ['Sapi/Kambing/Kerbau','Sapi/Kambing/Kerbau','Sapi/Kambing/Kerbau','Sapi/Kambing/Kerbau',
      'Unggas','Unggas','Unggas','Unggas','Unggas','Unggas',
      'Ikan','Ikan','Ikan','Ikan','Ikan','Ikan','Ikan',
      'Udang','Udang',
      'no_info']).astype(str)

#lahan_minimum
df['lahan_minimum'] = df['luas_lahan'].replace(['<1 Hektar','1-2 Hektar','2-5 Hektar','no_info'],
    ['1000','10000','20000','0']).astype(int)

#internet_minimum
df['internet_minimum'] = df['biaya_internet'].replace(['100-200 ribu','>300 ribu','<100 ribu','200-300 ribu','no_info'],['100000','300000','50000','200000','0']).astype(int)

"""MAKE INDEX FROM MAPPING THE CATEGORY OF EACH FEATURE"""

#MAPPING 
df['lokasi_idx'] = df['lokasi'].map(df['lokasi'].unique().tolist().index).astype(int)
df['hewan_ternak_idx'] = df['hewan_ternak_sub'].map(df['hewan_ternak_sub'].unique().tolist().index).astype(int)
df['lokasi_geografis_idx'] = df['lokasi_geografis'].map(df['lokasi_geografis'].unique().tolist().index).astype(int)
df['mengerti_hewan_idx'] = df['mengerti_hewan'].map(df['mengerti_hewan'].unique().tolist().index).astype(int)
df['tipe_usaha_kuliner_idx'] = df['tipe_usaha_kuliner'].map(df['tipe_usaha_kuliner'].unique().tolist().index).astype(int)
df['kemampuan_masak_idx'] = df['kemampuan_masak'].map(df['kemampuan_masak'].unique().tolist().index).astype(int)
df['penyimpanan_barang_idx'] = df['penyimpanan_barang'].map(df['penyimpanan_barang'].unique().tolist().index).astype(int)
df['sosial_media_idx'] = df['sosial_media'].map(df['sosial_media'].unique().tolist().index).astype(int)
df['toko_toserba_idx'] = df['toko_toserba'].map(df['toko_toserba'].unique().tolist().index).astype(int)
df['tipe_toko_idx'] = df['tipe_toko'].map(df['tipe_toko'].unique().tolist().index).astype(int)
df['tipe_usaha_lain_idx'] = df['tipe_usaha_lain'].map(df['tipe_usaha_lain'].unique().tolist().index).astype(int)

"""CHANGING THE POSITION OF COLUMN"""

#CHANGE COLUMN POSITION

col0a = df.pop('Modal')
df.insert(1, 'Modal', col0a)

col0b = df.pop('modal_minimum')
df.insert(2, 'modal_minimum', col0b)

col0c = df.pop('modal_maximum')
df.insert(3, 'modal_maximum', col0c)

col0d = df.pop('tingkat_persaingan')
df.insert(4, 'tingkat_persaingan', col0d)

col0e = df.pop('tingkat_persaingan_idx')
df.insert(5, 'tingkat_persaingan_idx', col0e)

col0f = df.pop('jumlah_pegawai')
df.insert(6, 'jumlah_pegawai', col0f)

col0g = df.pop('pegawai_minimum')
df.insert(7, 'pegawai_minimum', col0g)

col0h = df.pop('omset')
df.insert(8, 'omset', col0h)

col0i = df.pop('omset_minimum')
df.insert(9, 'omset_minimum', col0i)

col0j = df.pop('target_pasar')
df.insert(10, 'target_pasar', col0j)

col0k = df.pop('tp_b')
df.insert(11, 'tp_b', col0k)

col0l = df.pop('tp_m')
df.insert(12, 'tp_m', col0l)

col0m = df.pop('tp_a')
df.insert(13, 'tp_a', col0m)

col0n = df.pop('lokasi')
df.insert(14, 'lokasi', col0n)

col0 = df.pop('lokasi_idx')
df.insert(15, 'lokasi_idx', col0)

col1 = df.pop('hewan_ternak_sub')
df.insert(17, 'hewan_ternak_sub', col1)

col2 = df.pop('hewan_ternak_idx')
df.insert(18, 'hewan_ternak_idx', col2)

col31 = df.pop('lokasi_geografis')
df.insert(19, 'lokasi_geografis', col31)

col3 = df.pop('lokasi_geografis_idx')
df.insert(20, 'lokasi_geografis_idx', col3)

col41 = df.pop('mengerti_hewan')
df.insert(21, 'mengerti_hewan', col41)

col4 = df.pop('mengerti_hewan_idx')
df.insert(22, 'mengerti_hewan_idx', col4)

col51 = df.pop('luas_lahan')
df.insert(23, 'luas_lahan', col51)

col5 = df.pop('lahan_minimum')
df.insert(24, 'lahan_minimum', col5)

col61 = df.pop('usaha_kuliner')
df.insert(25, 'usaha_kuliner', col61)

col62 = df.pop('tipe_usaha_kuliner')
df.insert(26, 'tipe_usaha_kuliner', col62)

col6 = df.pop('tipe_usaha_kuliner_idx')
df.insert(27, 'tipe_usaha_kuliner_idx', col6)

col71 = df.pop('kemampuan_masak')
df.insert(28, 'kemampuan_masak', col71)

col7 = df.pop('kemampuan_masak_idx')
df.insert(29, 'kemampuan_masak_idx', col7)

col81 = df.pop('barang_dropship')
df.insert(30, 'barang_dropship', col81)

col82 = df.pop('penyimpanan_barang')
df.insert(31, 'penyimpanan_barang', col82)

col8 = df.pop('penyimpanan_barang_idx')
df.insert(32, 'penyimpanan_barang_idx', col8)

col91 = df.pop('biaya_internet')
df.insert(33, 'biaya_internet', col91)

col9 = df.pop('internet_minimum')
df.insert(34, 'internet_minimum', col9)

col10 = df.pop('sosial_media')
df.insert(35, 'sosial_media', col10)

col11 = df.pop('sosial_media_idx')
df.insert(36, 'sosial_media_idx', col11)

col121 = df.pop('barang_toserba')
df.insert(37, 'barang_toserba', col121)

col12 = df.pop('toko_toserba')
df.insert(38, 'toko_toserba', col12)

col13 = df.pop('toko_toserba_idx')
df.insert(39, 'toko_toserba_idx', col13)

col14 = df.pop('tipe_toko')
df.insert(40, 'tipe_toko', col14)

col15 = df.pop('tipe_toko_idx')
df.insert(41, 'tipe_toko_idx', col15)

col16 = df.pop('usaha_lain')
df.insert(42, 'usaha_lain', col16)

col17 = df.pop('tipe_usaha_lain')
df.insert(43, 'tipe_usaha_lain', col17)

col18 = df.pop('tipe_usaha_lain_idx')
df.insert(44, 'tipe_usaha_lain_idx', col18)

"""DROP UNNECESSARY COLUMN"""

#DROP COLUMN

df = df.drop(columns=['Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha sebagai peternak?',
 'Berapakah jumlah pegawai saat ini?',
 'Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?',
 'tarpas',
 'Berapa kira-kira keuntungan anda saat panen?',
 'Menurut Anda apa 3 hal terpenting yang harus dikuasai untuk menjadi Peternak?',
 'Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha sebagai pengusaha kuliner?',
 'Dimana lokasi anda berjualan?',
 'Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.1',
 'Berapakah jumlah pegawai saat ini?.1',
 'Kepada siapa anda menjual makanan/minuman anda? ',
 'Berapa kira-kira omset anda dalam 1 bulan?',
 'Menurut Anda apa 3 hal terpenting yang harus dikuasai untuk menjadi pengusaha kuliner? ',
 'Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha sebagai Dropshipper?',
 'Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.2',
 'Berapakah jumlah pegawai saat ini?.2',
 'Kepada siapa target pasar anda? ',
 'Berapa kira-kira omset anda dalam 1 bulan?.1',
 'Menurut Anda apa 3 hal terpenting yang harus dikuasai untuk menjadi Dropshipper?',
 'Berdasarkan pengalaman anda, berapakah modal yang anda keluarkan saat memulai usaha toserba?',
 'Dimana lokasi anda berjualan?.1',
 'Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.3',
 'Berapakah jumlah pegawai saat ini?.3',
 'Kepada siapa target pasar anda? .1',
 'Berapa kira-kira omset anda dalam 1 bulan?.2',
 'Menurut Anda apa 3 hal terpenting yang harus dikuasai untuk menjalani usaha Toserba? ',
 'Berdasarkan pengalaman anda, berapakah modal yang diperlukan untuk menjalankan usaha tersebut?',
 'Dimana lokasi usaha Anda berjalan?',
 'Menurut anda seperti apa tingkat persaingan dalam usaha tersebut?.4',
 'Berapakah jumlah pegawai saat ini?.4',
 'Kepada siapa target pasar anda? .2',
 'Berapa kira-kira omset anda dalam 1 bulan?.3',
 'Menurut Anda apa 3 hal terpenting yang harus dikuasai untuk menjalani usaha tersebut? ',
 'Apakah anda memiliki pendapat atau masukkan yang bisa ditambahkan terkait usaha yang anda jalani? (Opsional)'])

df.head()

df.dtypes

from google.colab import files
df.to_csv('Busaha_Dataset.csv') 
files.download("Busaha_Dataset.csv")